version: '3.3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'movie-dev'
      MYSQL_USER: 'usr-movie'
      MYSQL_PASSWORD: 'pwd-movie'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    healthcheck:
      test: [ "CMD", "usrseriey-mysql", "ping", "-ppwd-spotify-mysql", "--silent" ]
      interval: 5s
      timeout: 3s
      retries: 10
  mongocontenedor:
    image: mongo
    container_name: mongocontenedor
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'seriedevmongo'
      MONGO_INITDB_ROOT_USERNAME: 'usrseriemongo'
      MONGO_INITDB_ROOT_PASSWORD: 'pwdseriemongo'
    ports:
      - 27017:27017
    expose:
      - 27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  zipkin-contenedor:
    image: openzipkin/zipkin-slim
    container_name: zipkin-contenedor
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    expose:
      - 9411
    depends_on:
      - storage-contenedor
  storage-contenedor:
    image: busybox:1.31.0
    container_name: storage-contenedor

  rabbitmq-contenedor:
    image: rabbitmq:3-management
    container_name: rabbitmq-contenedor
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    expose:
      - 15672
      - 5672