server:
  port: 8888
spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/VickyStancic/ParcialStancicVictoria
          search-paths: ParcialStancicVictoria/ConfigData/
          force-pull: true
          default-label: develop
