server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: api-serie
  zipkin:
    baseUrl: http://localhost:9411/
    enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

  data:
    mongodb:
      database: seriedevmongo
      port: 27017
      host: localhost

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${random.int}

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true

info:
  app:
    name: api series
    version: 1.0.0
    description: Series